### PR TITLE
Fix: Allow for object with buffer property

### LINKED ISSUE #6: TypeError: The provided value is not of type '(ArrayBuffer or ArrayBufferView)
Hi. First off, thanks for a great set of libraries.

Ran into an issue when using `@peculiar/x509`:
```
TypeError: The provided value is not of type '(ArrayBuffer or ArrayBufferView)'
  at Function.toView (../node_modules/pvtsutils/build/index.js:35:17)
  at Function.toUint8Array (../node_modules/pvtsutils/build/index.js:23:23)
  at Function.ToHex (../node_modules/pvtsutils/build/index.js:166:45)
  at AuthorityKeyIdentifierExtension.onInit (../node_modules/@peculiar/x509/build/x509.cjs.js:671:44)
  at new AsnData (../node_modules/@peculiar/x509/build/x509.cjs.js:51:18)
  at new Extension (../node_modules/@peculiar/x509/build/x509.cjs.js:75:9)
  at new AuthorityKeyIdentifierExtension (../node_modules/@peculiar/x509/build/x509.cjs.js:645:13)
```

Tracked it down to these LoCs in `@peculiar/x509`: https://github.com/PeculiarVentures/x509/blob/master/src/extensions/authority_key_identifier.ts#L104-L107

And to this function in `pvtsutils`: https://github.com/PeculiarVentures/pvtsutils/blob/master/src/buffer_source_converter.ts#L35-L46

Should the `toView` method also accept an object-like input like `{ buffer: ArrayBuffer }`? 

Found a similar piece of code that accepts it this way: https://github.com/PeculiarVentures/asn1-schema/blob/988241d5c3c8fa4ef6f581b55b7354330ead0156/packages/schema/src/parser.ts#L27

### PR DESCRIPTION
**Pull request by johannessjoberg**
Fixes #6

### CODE REVIEW

**Comment by microshine** [comment]
@johannessjoberg Thank you for your PR

The new version is available 
```
pvtsutils@1.1.5
```

**Comment by johannessjoberg** [comment]
@microshine Thanks! Will you also release a new version of `@peculiar/x509` and other consumers of `pvtsutils`?

**Comment by microshine** [comment]
I published a `patch` version. I think it doesn't require updating all other module dependencies

**Comment by johannessjoberg** [comment]
Ah, that makes sense. Thanks again :)

**Pull request merged**
